name = "Zeta5"
version = "0.1.0"
license = "(Apache-2.0 OR MIT)"
keywords = ["math"]
defaultTargets = ["Zeta5"]
testDriver = "Zeta5Test"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header.license = "Released under Apache 2.0 or MIT license, at your option, as described in the file COPYRIGHT."
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0"

[[lean_lib]]
name = "Zeta5"

[[lean_lib]]
name = "Zeta5Test"
