# /// script
# requires-python = ">=3.11"
# dependencies = ["python-flint>=0.7"]
# ///
"""Generate `Zeta5/PotentialData.lean`: the sorted endpoints of the intervals of Table 2.

Run: `uv run scripts/gen_table2.py`.
"""

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("cp", ROOT / "scripts" / "check_potential.py")
cp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cp)

ivs = cp.table2_intervals()
pts = sorted({l for _, l, _ in ivs} | {r for _, _, r in ivs})
assert pts[0] == 0 and pts[-1] == 2
body = ",\n  ".join(f"({p.numerator}, {p.denominator})" for p in pts)
n = len(pts)
out = f'''/-
Copyright (c) 2026 Jihyeon Kim. All rights reserved.
Released under Apache 2.0 or MIT license, at your option, as described in the file COPYRIGHT.
Authors: Jihyeon Kim
-/
import Mathlib.Data.Rat.Defs

/-!
# The partition of Table 2

The {n} endpoints `0 = p₀ < p₁ < ⋯ < p_{n - 1} = 2` of the {len(ivs)} intervals of Table 2 of the paper,
in increasing order. The interval `(j, d, k)` of the table is
`[A_j + (A_{{j+1}} - A_j) k/2^d, A_j + (A_{{j+1}} - A_j)(k+1)/2^d]` with `A₀ = 0`, `A_j = a_{{17-j}}`
(`1 ≤ j ≤ 16`), `A₁₇ = q₋`, `A₁₈ = q₊`, `A_{{18+j}} = b_j`, `A₃₅ = 2`.

This file is generated by `scripts/gen_table2.py`. Its correctness does not matter for the proof:
`Zeta5.checkChain` verifies the potential inequality on every interval `[p_i, p_{{i+1}}]` of whatever
list it is given, and the list only has to start at `0` and end at `2`.
-/

namespace Zeta5

/-- The endpoints of the intervals of Table 2, in increasing order, as numerator-denominator
pairs. -/
def table2Raw : List (ℕ × ℕ) := [
  {body}]

/-- The endpoints of the intervals of Table 2, in increasing order. -/
def table2Points : List ℚ := table2Raw.map fun p => (p.1 : ℚ) / p.2

end Zeta5
'''
(ROOT / "Zeta5" / "PotentialData.lean").write_text(out)
print(f"wrote {n} points")
